
</head>
<body>

<div class="container">
    <nav class="navbar">
        <div class="navbar-inner">
            <div class="container">
                <a href="http://www.govgit.info" class="brand">GovGit Clone</a>
                    <ul class="nav">
                        <li id="overview"><a href=".">Overview</a></li>
                        <li><a href="map.php">Map</a></li>
                        <li><a href="">Link #3</a></li>
                        <li><a href="">Link with looooooooooooooong name</a></li>

                    </ul>
            </div>
        </div>
    </nav>
